<a href="https://colab.research.google.com/github/samitha278/multilayer-perceptron-char-lm/blob/main/mlp_char_lm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [134]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

In [135]:
from google.colab import files

uploaded = files.upload()


Saving names.txt to names (3).txt


In [136]:
words = open("names.txt","r").read().splitlines()

In [137]:
chars = sorted(list(set("".join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi["."] = 0
itos = {i:s for s,i in stoi.items()}
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

### Building dataset

In [138]:
block_size = 3


xs = []
ys = []


context = [0]*block_size



for w in words:

  for ch in w + '.':

    xs.append(context)
    next = stoi[ch]
    ys.append(next)


    context = context[1:] + [next]


x = torch.tensor(xs)
y = torch.tensor(ys)

In [139]:
x.shape,y.shape

(torch.Size([228146, 3]), torch.Size([228146]))

In [140]:
x[:5]

tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        [ 5, 13, 13],
        [13, 13,  1]])

### Embedding

In [141]:
g = torch.Generator().manual_seed(2147483647)

In [142]:
C = torch.randn((27,2),generator=g,requires_grad=True)
C

tensor([[ 1.5674, -0.2373],
        [-0.0274, -1.1008],
        [ 0.2859, -0.0296],
        [-1.5471,  0.6049],
        [ 0.0791,  0.9046],
        [-0.4713,  0.7868],
        [-0.3284, -0.4330],
        [ 1.3729,  2.9334],
        [ 1.5618, -1.6261],
        [ 0.6772, -0.8404],
        [ 0.9849, -0.1484],
        [-1.4795,  0.4483],
        [-0.0707,  2.4968],
        [ 2.4448, -0.6701],
        [-1.2199,  0.3031],
        [-1.0725,  0.7276],
        [ 0.0511,  1.3095],
        [-0.8022, -0.8504],
        [-1.8068,  1.2523],
        [ 0.1476, -1.0006],
        [-0.5030, -1.0660],
        [ 0.8480,  2.0275],
        [-0.1158, -1.2078],
        [-1.0406, -1.5367],
        [-0.5132,  0.2961],
        [-1.4904, -0.2838],
        [ 0.2569,  0.2130]], requires_grad=True)

In [143]:
C[5]

tensor([-0.4713,  0.7868], grad_fn=<SelectBackward0>)

In [144]:
C[torch.tensor([2,3,5,5,5])]

tensor([[ 0.2859, -0.0296],
        [-1.5471,  0.6049],
        [-0.4713,  0.7868],
        [-0.4713,  0.7868],
        [-0.4713,  0.7868]], grad_fn=<IndexBackward0>)

In [145]:
C[torch.tensor([[2,3],[3,2],[5,5],[2,5]])]

tensor([[[ 0.2859, -0.0296],
         [-1.5471,  0.6049]],

        [[-1.5471,  0.6049],
         [ 0.2859, -0.0296]],

        [[-0.4713,  0.7868],
         [-0.4713,  0.7868]],

        [[ 0.2859, -0.0296],
         [-0.4713,  0.7868]]], grad_fn=<IndexBackward0>)

In [146]:
emb = C[x]
emb.shape

torch.Size([228146, 3, 2])

In [147]:
x[1],C[[0,5]],emb[1]

(tensor([0, 0, 5]),
 tensor([[ 1.5674, -0.2373],
         [-0.4713,  0.7868]], grad_fn=<IndexBackward0>),
 tensor([[ 1.5674, -0.2373],
         [ 1.5674, -0.2373],
         [-0.4713,  0.7868]], grad_fn=<SelectBackward0>))

### Preparing input neurons to feed hidden layer

In [148]:
emb[:5]

tensor([[[ 1.5674, -0.2373],
         [ 1.5674, -0.2373],
         [ 1.5674, -0.2373]],

        [[ 1.5674, -0.2373],
         [ 1.5674, -0.2373],
         [-0.4713,  0.7868]],

        [[ 1.5674, -0.2373],
         [-0.4713,  0.7868],
         [ 2.4448, -0.6701]],

        [[-0.4713,  0.7868],
         [ 2.4448, -0.6701],
         [ 2.4448, -0.6701]],

        [[ 2.4448, -0.6701],
         [ 2.4448, -0.6701],
         [-0.0274, -1.1008]]], grad_fn=<SliceBackward0>)

In [149]:
emb[:5,0]

tensor([[ 1.5674, -0.2373],
        [ 1.5674, -0.2373],
        [ 1.5674, -0.2373],
        [-0.4713,  0.7868],
        [ 2.4448, -0.6701]], grad_fn=<SelectBackward0>)

In [150]:
torch.cat([emb[:5,0],emb[:5,1],emb[:5,2]],dim=1)

tensor([[ 1.5674, -0.2373,  1.5674, -0.2373,  1.5674, -0.2373],
        [ 1.5674, -0.2373,  1.5674, -0.2373, -0.4713,  0.7868],
        [ 1.5674, -0.2373, -0.4713,  0.7868,  2.4448, -0.6701],
        [-0.4713,  0.7868,  2.4448, -0.6701,  2.4448, -0.6701],
        [ 2.4448, -0.6701,  2.4448, -0.6701, -0.0274, -1.1008]],
       grad_fn=<CatBackward0>)

In [151]:
torch.cat([emb[:,0],emb[:,1],emb[:,2]],dim=1).shape

torch.Size([228146, 6])

In [152]:
torch.cat(torch.unbind(emb,1),1).shape

torch.Size([228146, 6])

### torch view and storage

In [153]:
a = torch.arange(12)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [154]:
a.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 12]

In [155]:
a.view(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [156]:
#only view has been changed memory allocation of a is same as before

# https://blog.ezyang.com/2019/05/pytorch-internals/

a.view(3,4).storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 12]

### Implementing hidden layer

In [157]:
W1 = torch.randn((6,100),generator=g,requires_grad=True)
b1 = torch.randn(100,generator=g,requires_grad=True)

In [158]:
h = torch.tanh(emb.view(-1,6) @ W1 + b1)

In [159]:
h.shape , h

(torch.Size([228146, 100]),
 tensor([[-0.9348,  1.0000,  0.9258,  ...,  0.9786, -0.1926,  0.9515],
         [ 0.2797,  0.9997,  0.7675,  ...,  0.9929,  0.9992,  0.9981],
         [-0.9960,  1.0000, -0.8694,  ..., -0.5159, -1.0000, -0.0069],
         ...,
         [-0.4849,  0.9972, -0.6418,  ..., -0.9641,  0.9996,  0.9873],
         [-0.9318,  0.9926, -0.9841,  ..., -0.8989, -0.9938,  0.5930],
         [-0.9736,  0.3844, -0.8744,  ..., -0.5093,  0.9998, -0.9975]],
        grad_fn=<TanhBackward0>))

### Output layer

In [160]:
W2 = torch.randn((100,27),generator=g,requires_grad=True)
b2 = torch.randn(27,generator=g,requires_grad=True)

In [161]:
logits = h @ W2 + b2
logits.shape

torch.Size([228146, 27])

### Softmax

In [162]:
p = logits.exp()
p /= p.sum(1,keepdim=True)

p.shape

torch.Size([228146, 27])

### Loss

In [163]:
loss = -p[torch.arange(p.shape[0]),y].log().mean()
loss

tensor(19.2358, grad_fn=<NegBackward0>)

### Efficient way to calculate Loss

In [164]:
loss = F.cross_entropy(logits,y)
loss

tensor(19.2358, grad_fn=<NllLossBackward0>)

### Backpropagation

In [165]:
parameters = [C,W1,b1,W2,b2]

In [166]:
for p in parameters:

  #p.requires_grad = True
  #don't set requires_grad here → must be set at init time,
  #otherwise loss won't track this param in the graph

  #fixed it , remember it

  p.grad = None

In [167]:
loss.backward()

## What’s happening under the hood?

* When you create a parameter with requires_grad=True, PyTorch starts tracking
every operation involving it and builds a computation graph.

* During loss.backward(), PyTorch walks backward through this graph and fills in p.grad for each parameter.

* Gradients accumulate in .grad (they don’t overwrite). That’s why we set p.grad = None before each backward pass.

* If you accidentally set requires_grad=True after the forward pass, the computation graph was already built without tracking, so no grads flow → loss.backward() fails.

In [168]:
for p in parameters:
  p.data -= 0.01 * p.grad

### Forward pass

In [169]:
h = torch.tanh(emb.view(-1,6) @ W1 + b1 )
logits = h @ W2 +b2
loss = F.cross_entropy(logits,y)
loss                  #decreased liltle bit

tensor(19.1409, grad_fn=<NllLossBackward0>)

# START OVER

In [170]:
x.shape , y.shape

(torch.Size([228146, 3]), torch.Size([228146]))

In [171]:
g = torch.Generator().manual_seed(2147483647)
C = torch.randn((27,2),generator=g,requires_grad=True)
W1 = torch.randn((6,100),generator=g,requires_grad=True)
b1 = torch.randn(100,generator=g,requires_grad=True)
W2 = torch.randn((100,27),generator=g,requires_grad=True)
b2 = torch.randn(27,generator=g,requires_grad=True)
parameters = [C,W1,b1,W2,b2]

In [172]:
sum([p.nelement() for p in parameters])    #parameters

3481

In [173]:
for _ in range(100):


  #forward
  emb = C[x]
  h = torch.tanh(emb.view(-1,6) @ W1 + b1)
  logits = h @ W2 + b2

  loss = F.cross_entropy(logits,y)
  print(loss.item())

  #backward
  for p in parameters:
    p.grad = None

  loss.backward()

  #update
  for p in parameters:
    p.data -= 0.1 * p.grad



19.235767364501953
18.205913543701172
17.299165725708008
16.491422653198242
15.758025169372559
15.081764221191406
14.455564498901367
13.874733924865723
13.335489273071289
12.834827423095703
12.369384765625
11.935105323791504
11.52763557434082
11.143498420715332
10.780662536621094
10.438188552856445
10.115513801574707
9.811923027038574
9.526389122009277
9.257646560668945
9.004351615905762
8.765169143676758
8.53882884979248
8.32414722442627
8.12004280090332
7.925546169281006
7.7398152351379395
7.562122821807861
7.3918561935424805
7.228500843048096
7.071640968322754
6.920960903167725
6.776233673095703
6.637332916259766
6.504215717315674
6.376900672912598
6.255455017089844
6.139944553375244
6.030381202697754
5.926675319671631
5.828596591949463
5.735793113708496
5.647831439971924
5.564256191253662
5.484630584716797
5.408565044403076
5.335723400115967
5.265822887420654
5.198623180389404
5.133925437927246
5.07155704498291
5.011370658874512
4.9532389640808105
4.8970465660095215
4.8426942825317