<a href="https://colab.research.google.com/github/samitha278/multilayer-perceptron-char-lm/blob/main/mlp_char_lm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

In [3]:
from google.colab import files

uploaded = files.upload()


Saving names.txt to names (1).txt


In [4]:
words = open("names.txt","r").read().splitlines()

In [5]:
chars = sorted(list(set("".join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi["."] = 0
itos = {i:s for s,i in stoi.items()}
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

### Building dataset

In [6]:
block_size = 3


xs = []
ys = []


context = [0]*block_size



for w in words:

  for ch in w + '.':

    xs.append(context)
    next = stoi[ch]
    ys.append(next)


    context = context[1:] + [next]


x = torch.tensor(xs)
y = torch.tensor(ys)

In [7]:
x.shape,y.shape

(torch.Size([228146, 3]), torch.Size([228146]))

In [8]:
x[:5]

tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        [ 5, 13, 13],
        [13, 13,  1]])

### Embedding

In [69]:
g = torch.Generator().manual_seed(2147483647)

In [70]:
C = torch.randn((27,2),generator=g,requires_grad=True)
C

tensor([[ 1.5674, -0.2373],
        [-0.0274, -1.1008],
        [ 0.2859, -0.0296],
        [-1.5471,  0.6049],
        [ 0.0791,  0.9046],
        [-0.4713,  0.7868],
        [-0.3284, -0.4330],
        [ 1.3729,  2.9334],
        [ 1.5618, -1.6261],
        [ 0.6772, -0.8404],
        [ 0.9849, -0.1484],
        [-1.4795,  0.4483],
        [-0.0707,  2.4968],
        [ 2.4448, -0.6701],
        [-1.2199,  0.3031],
        [-1.0725,  0.7276],
        [ 0.0511,  1.3095],
        [-0.8022, -0.8504],
        [-1.8068,  1.2523],
        [ 0.1476, -1.0006],
        [-0.5030, -1.0660],
        [ 0.8480,  2.0275],
        [-0.1158, -1.2078],
        [-1.0406, -1.5367],
        [-0.5132,  0.2961],
        [-1.4904, -0.2838],
        [ 0.2569,  0.2130]], requires_grad=True)

In [71]:
C[5]

tensor([-0.4713,  0.7868], grad_fn=<SelectBackward0>)

In [11]:
C[torch.tensor([2,3,5,5,5])]

tensor([[ 0.1016,  0.0644],
        [-1.0396, -2.8078],
        [ 0.6209,  0.8554],
        [ 0.6209,  0.8554],
        [ 0.6209,  0.8554]])

In [12]:
C[torch.tensor([[2,3],[3,2],[5,5],[2,5]])]

tensor([[[ 0.1016,  0.0644],
         [-1.0396, -2.8078]],

        [[-1.0396, -2.8078],
         [ 0.1016,  0.0644]],

        [[ 0.6209,  0.8554],
         [ 0.6209,  0.8554]],

        [[ 0.1016,  0.0644],
         [ 0.6209,  0.8554]]])

In [13]:
emb = C[x]
emb.shape

torch.Size([228146, 3, 2])

In [14]:
x[1],C[[0,5]],emb[1]

(tensor([0, 0, 5]),
 tensor([[-0.3267,  1.8026],
         [ 0.6209,  0.8554]]),
 tensor([[-0.3267,  1.8026],
         [-0.3267,  1.8026],
         [ 0.6209,  0.8554]]))

### Preparing input neurons to feed hidden layer

In [15]:
emb[:5]

tensor([[[-0.3267,  1.8026],
         [-0.3267,  1.8026],
         [-0.3267,  1.8026]],

        [[-0.3267,  1.8026],
         [-0.3267,  1.8026],
         [ 0.6209,  0.8554]],

        [[-0.3267,  1.8026],
         [ 0.6209,  0.8554],
         [-0.1046, -0.6759]],

        [[ 0.6209,  0.8554],
         [-0.1046, -0.6759],
         [-0.1046, -0.6759]],

        [[-0.1046, -0.6759],
         [-0.1046, -0.6759],
         [-1.6643,  0.3641]]])

In [16]:
emb[:5,0]

tensor([[-0.3267,  1.8026],
        [-0.3267,  1.8026],
        [-0.3267,  1.8026],
        [ 0.6209,  0.8554],
        [-0.1046, -0.6759]])

In [17]:
torch.cat([emb[:5,0],emb[:5,1],emb[:5,2]],dim=1)

tensor([[-0.3267,  1.8026, -0.3267,  1.8026, -0.3267,  1.8026],
        [-0.3267,  1.8026, -0.3267,  1.8026,  0.6209,  0.8554],
        [-0.3267,  1.8026,  0.6209,  0.8554, -0.1046, -0.6759],
        [ 0.6209,  0.8554, -0.1046, -0.6759, -0.1046, -0.6759],
        [-0.1046, -0.6759, -0.1046, -0.6759, -1.6643,  0.3641]])

In [18]:
torch.cat([emb[:,0],emb[:,1],emb[:,2]],dim=1).shape

torch.Size([228146, 6])

In [19]:
torch.cat(torch.unbind(emb,1),1).shape

torch.Size([228146, 6])

### torch view and storage

In [20]:
a = torch.arange(12)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
a.storage()

/tmp/ipython-input-214256462.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  a.storage()


 0
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 12]

In [22]:
a.view(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [23]:
#only view has been changed memory allocation of a is same as before

# https://blog.ezyang.com/2019/05/pytorch-internals/

a.view(3,4).storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 12]

### Implementing hidden layer

In [73]:
W1 = torch.randn((6,100),generator=g,requires_grad=True)
b1 = torch.randn(100,generator=g,requires_grad=True)

In [25]:
h = torch.tanh(emb.view(-1,6) @ W1 + b1)

In [26]:
h.shape , h

(torch.Size([228146, 100]),
 tensor([[ 0.9678, -1.0000, -0.9977,  ..., -0.7191,  0.9954,  0.8426],
         [-0.5085, -1.0000, -0.8353,  ...,  0.7963,  0.9315,  0.8379],
         [-0.9831, -0.9999, -0.9747,  ...,  0.8230,  0.9207, -0.7672],
         ...,
         [-0.8871, -0.5687,  0.5086,  ..., -0.9093, -0.9216, -0.9876],
         [-0.3703, -0.6264,  0.8375,  ..., -0.9918, -0.2505, -0.9677],
         [ 0.9923, -0.9831,  0.7876,  ..., -0.9978,  0.3601,  0.9394]]))

### Output layer

In [74]:
W2 = torch.randn((100,27),generator=g,requires_grad=True)
b2 = torch.randn(27,generator=g,requires_grad=True)

In [28]:
logits = h @ W2 + b2
logits.shape

torch.Size([228146, 27])

### Softmax

In [29]:
p = logits.exp()
p /= p.sum(1,keepdim=True)

p.shape

torch.Size([228146, 27])

### Loss

In [59]:
loss = -p[torch.arange(p.shape[0]),y].log().mean()
loss

tensor(18.2166)

### Efficient way to calculate Loss

In [63]:
loss = F.cross_entropy(logits,y)
loss

tensor(18.2166)

### Bcckpropagation

In [65]:
parameters = [C,W1,b1,W2,b2]

In [67]:
for p in parameters:

  #p.requires_grad = True
  # don't set requires_grad here → must be set at init time,
  # otherwise loss won't track this param in the graph

  #fixed it , remember it

  p.grad = None

In [68]:
loss.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

## What’s happening under the hood?

* When you create a parameter with requires_grad=True, PyTorch starts tracking
every operation involving it and builds a computation graph.

* During loss.backward(), PyTorch walks backward through this graph and fills in p.grad for each parameter.

* Gradients accumulate in .grad (they don’t overwrite). That’s why we set p.grad = None before each backward pass.

* If you accidentally set requires_grad=True after the forward pass, the computation graph was already built without tracking, so no grads flow → loss.backward() fails.

### Try again backprop with